services:
  iperf3:
    image: registry.internal.dannyshih.net:5000/iperf3:v3.16
    container_name: iperf3
    build: .
    platform: linux/amd64
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 5201:5201
